name: Version Check
description: Ensures version.go version > latest Git tag
runs:
  using: "composite"
  steps:
  - name: Fetch all tags
    shell: bash
    run: git fetch --tags

  - name: Read version from version.go
    id: read_version
    shell: bash
    run: |
      VERSION=$(grep 'Version =' version.go | sed -E 's/.*"(.+)"$/\1/')
      echo "Found version: $VERSION"
      echo "version=$VERSION" >> $GITHUB_OUTPUT

  - name: Get latest Git tag
    id: latest_tag
    shell: bash
    run: |
      TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
      echo "Latest tag: $TAG"
      echo "tag=$TAG" >> $GITHUB_OUTPUT

  - name: Compare version with latest tag
    shell: bash
    run: |
      if [ "${{ steps.read_version.outputs.version }}" = "${{ steps.latest_tag.outputs.tag }}" ]; then
        echo "::error::Version in version.go is same as latest Git tag. Bump required."
        exit 1
      fi
